[[rulesets]]
group = "â“‚ï¸ Onedrive"
type = "clash-classic"
ruleset = "https://raw.githubusercontent.com/Centralmatrix3/Matrix-io/master/Clash/Ruleset/Onedrive.yaml"

[[rulesets]]
group = "ğŸ Apple"
type = "clash-classic"
ruleset = "https://raw.githubusercontent.com/Centralmatrix3/Matrix-io/master/Clash/Ruleset/Apple.yaml"

[[rulesets]]
group = "ğŸ›°ï¸ èŠ‚ç‚¹é€‰æ‹©"
type = "clash-classic"
ruleset = "https://raw.githubusercontent.com/Centralmatrix3/Matrix-io/master/Clash/Ruleset/GoogleCN.yaml"

[[rulesets]]
group = "ğŸ›°ï¸ èŠ‚ç‚¹é€‰æ‹©"
type = "clash-classic"
ruleset = "https://raw.githubusercontent.com/Centralmatrix3/Matrix-io/master/Clash/Ruleset/GlobalMax.yaml"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "rules/LocalAreaNetwork.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
type = "clash-classic"
ruleset = "https://raw.githubusercontent.com/Centralmatrix3/Matrix-io/master/Clash/Ruleset/China.yaml"

[[rulesets]]
group = "ğŸ›‘ å…¨çƒæ‹¦æˆª"
type = "clash-domain"
ruleset = "https://raw.githubusercontent.com/Centralmatrix3/Matrix-io/master/Clash/Ruleset/AdBlock.yaml"

[[rulesets]]
group = "ğŸ›‘ å…¨çƒæ‹¦æˆª"
type = "clash-domain"
ruleset = "https://raw.githubusercontent.com/Centralmatrix3/Matrix-io/master/Clash/Ruleset/REJECT.yaml"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
type = "clash-classic"
ruleset = "https://raw.githubusercontent.com/Centralmatrix3/Matrix-io/master/Clash/Ruleset/ChinaIPMax.yaml"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "[]GEOIP,CN,no-resolve"

[[rulesets]]
group = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
ruleset = "[]FINAL"
