[[rulesets]]
group = "â“‚ï¸ Onedrive"
type = "clash-classic"
ruleset = "https://raw.githubusercontent.com/Centralmatrix3/Matrix-io/master/Clash/Ruleset/Onedrive.yaml"

[[rulesets]]
group = "ğŸ Apple"
type = "clash-classic"
ruleset = "https://raw.githubusercontent.com/Centralmatrix3/Matrix-io/master/Clash/Ruleset/Apple.yaml"

[[rulesets]]
group = "ğŸ›°ï¸ èŠ‚ç‚¹é€‰æ‹©"
type = "clash-classic"
ruleset = "https://raw.githubusercontent.com/Centralmatrix3/Matrix-io/master/Clash/Ruleset/GoogleCN.yaml"

[[rulesets]]
group = "ğŸ›°ï¸ èŠ‚ç‚¹é€‰æ‹©"
type = "clash-classic"
ruleset = "https://raw.githubusercontent.com/Centralmatrix3/Matrix-io/master/Clash/Ruleset/GlobalMax.yaml"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
type = "clash-classic"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/LocalAreaNetwork.yaml"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
type = "clash-classic"
ruleset = "https://raw.githubusercontent.com/Centralmatrix3/Matrix-io/master/Clash/Ruleset/China.yaml"

[[rulesets]]
group = "ğŸ›‘ å…¨çƒæ‹¦æˆª"
type = "clash-domain"
ruleset = "https://raw.githubusercontent.com/Centralmatrix3/Matrix-io/master/Clash/Ruleset/AdBlock.yaml"

[[rulesets]]
group = "ğŸ›‘ å…¨çƒæ‹¦æˆª"
type = "clash-domain"
ruleset = "https://raw.githubusercontent.com/Centralmatrix3/Matrix-io/master/Clash/Ruleset/REJECT.yaml"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
type = "clash-classic"
ruleset = "https://raw.githubusercontent.com/Centralmatrix3/Matrix-io/master/Clash/Ruleset/ChinaIPMax.yaml"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "[]GEOIP,CN,no-resolve"

[[rulesets]]
group = "ğŸ‡­ğŸ‡° é¦™æ¸¯"
ruleset = ["(æ¸¯|HK|hk|Hong Kong|HongKong|hongkong|HKG)"]

[[rulesets]]
group = "ğŸ‡¯ğŸ‡µ æ—¥æœ¬"
ruleset = ["(æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|[^-]æ—¥|JP|Japan)"]

[[rulesets]]
group = "ğŸ‡ºğŸ‡² ç¾å›½"
ruleset = ["(ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|US|United States|ATL|BUF|DFW|EWR|IAD|LAX|MCI|MIA|ORD|PHX|PDX|SEA|SJC)"]

[[rulesets]]
group = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
ruleset = "[]FINAL"
