[[custom_groups]]
name = "ğŸ›°ï¸ èŠ‚ç‚¹é€‰æ‹©"
type = "select"
rule = ["[]DIRECT", "[]ğŸš€ æ‰‹åŠ¨é€‰æ‹©"]

[[custom_groups]]
name = "ğŸš€ æ‰‹åŠ¨é€‰æ‹©"
type = "select"
rule = [".*"]

[[custom_groups]]
name = "â“‚ï¸ Onedrive"
type = "select"
rule = ["[]ğŸ›°ï¸ èŠ‚ç‚¹é€‰æ‹©",
"[]ğŸ¯ å…¨çƒç›´è¿"
]

[[custom_groups]]
name = "ğŸ Apple"
type = "select"
rule = ["[]ğŸ›°ï¸ èŠ‚ç‚¹é€‰æ‹©",
"[]ğŸ¯ å…¨çƒç›´è¿",
]

[[custom_groups]]
name = "ğŸ›‘ å…¨çƒæ‹¦æˆª"
type = "select"
rule = ["[]REJECT", "[]DIRECT", "[]ğŸ›°ï¸ èŠ‚ç‚¹é€‰æ‹©"]

[[custom_groups]]
name = "ğŸ¯ å…¨çƒç›´è¿"
type = "select"
rule = ["[]DIRECT",
"[]ğŸ›°ï¸ èŠ‚ç‚¹é€‰æ‹©"
]

[[custom_groups]]
name = "ğŸ‡­ğŸ‡° é¦™æ¸¯"
type = "select"
rule = ["(æ¸¯|HK|hk|Hong Kong|HongKong|hongkong|HKG)"]

[[custom_groups]]
name = "ğŸ‡¯ğŸ‡µ æ—¥æœ¬"
type = "select"
rule = ["(æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|[^-]æ—¥|JP|Japan)"]

[[custom_groups]]
name = "ğŸ‡ºğŸ‡² ç¾å›½"
type = "select"
rule = ["(ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|US|United States|ATL|BUF|DFW|EWR|IAD|LAX|MCI|MIA|ORD|PHX|PDX|SEA|SJC)"]

[[custom_groups]]
name = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
type = "select"
rule = ["[]ğŸ›°ï¸ èŠ‚ç‚¹é€‰æ‹©",
"[]ğŸ¯ å…¨çƒç›´è¿",
]
