[[custom_groups]]
name = "🛰️ 节点选择"
type = "select"
rule = ["[]DIRECT", "[]🚀 手动选择", "[]🇭🇰 香港节点", "[]🇯🇵 日本节点", "[]🇺🇲 美国节点"]

[[custom_groups]]
name = "🚀 手动选择"
type = "select"
rule = [".*"]

[[custom_groups]]
name = "Ⓜ️ Onedrive"
type = "select"
rule = ["[]🛰️ 节点选择",
"[]🎯 全球直连"
]

[[custom_groups]]
name = "🍎 Apple"
type = "select"
rule = ["[]🛰️ 节点选择",
"[]🎯 全球直连",
]

[[custom_groups]]
name = "🛑 全球拦截"
type = "select"
rule = ["[]REJECT", "[]DIRECT", "[]🛰️ 节点选择"]

[[custom_groups]]
name = "🎯 全球直连"
type = "select"
rule = ["[]DIRECT",
"[]🛰️ 节点选择"
]

[[custom_groups]]
name = "🇭🇰 香港节点"
type = "select"
rule = ["[]DIRECT", "(港|HK|hk|Hong Kong|HongKong|hongkong|HKG)"]

[[custom_groups]]
name = "🇯🇵 日本节点"
type = "select"
rule = ["[]DIRECT", "(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan)"]

[[custom_groups]]
name = "🇺🇲 美国节点"
type = "select"
rule = ["[]DIRECT", "(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|America|ATL|BUF|DFW|EWR|IAD|LAX|MCI|MIA|ORD|PHX|PDX|SEA|SJC)"]

[[custom_groups]]
name = "🐟 漏网之鱼"
type = "select"
rule = ["[]🛰️ 节点选择",
"[]🎯 全球直连",
]
